name: Build OpenBLAS

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  openblas_windows:
    name: Build OpenBLAS on Windows
    runs-on: windows-latest
    env: 
      OPENBLAS_VERSION: 0.3.28
    strategy: 
      matrix:
        target:
          - name: x64
            opts: "-DBINARY=64 -DUSE_THREAD=OFF -DUSE_LOCKING=ON"
          - name: x86
            opts: "-DBINARY=32 -DUSE_THREAD=OFF -DUSE_LOCKING=ON"
          - name: x64-64
            opts: "-DBINARY=64 -DUSE_THREAD=ON -DNUM_THREADS=64"
    steps:
      - name: Extract branch name
        shell: bash
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
        id: extract_branch

      - name: Cache conda
        uses: actions/cache@v3
        env:
          # Increase this value to reset cache if etc/example-environment.yml has not changed
          CACHE_NUMBER: 0
        with:
          enableCrossOsArchive: true
          path: D:\conda_pkgs_dir
          key:
            ${{ runner.os }}-conda-${{ env.CACHE_NUMBER }}

      - name: download and unzip OpenBLAS 
        run: |
          curl -LO "https://github.com/OpenMathLib/OpenBLAS/releases/download/v${{ env.OPENBLAS_VERSION }}/OpenBLAS-${{ env.OPENBLAS_VERSION }}.zip"
          7z x "OpenBLAS-${{ env.OPENBLAS_VERSION }}.zip"
          mv "OpenBLAS-${{ env.OPENBLAS_VERSION }}" OpenBLAS

      - name: Set Up Miniconda
        uses: conda-incubator/setup-miniconda@v3
        with: 
          pkgs-dirs: D:\conda_pkgs_dir
          auto-activate-base: true
          activate-environment: ""

      - name: Get Latest CMake and Ninja
        uses: lukka/get-cmake@latest

      - name: Install Conda Packages
        run: |
          conda config --add channels conda-forge --force
          conda config --set auto_update_conda false
          conda install --yes --quiet cmake flang clangdev perl libflang ninja

      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v2

      - name: Configure CMake
        run: |
          conda activate
          set "LIB=${{ env.CONDA }}\Library\lib;%LIB%"
          set "CPATH=${{ env.CONDA }}\Library\include;%CPATH%"
          dir OpenBLAS
          cd OpenBLAS
          mkdir build
          cd build
          
          $commonArgs = "-DCMAKE_CXX_COMPILER=clang-cl -DCMAKE_C_COMPILER=clang-cl -DCMAKE_Fortran_COMPILER=flang -DCMAKE_MT=mt -DBUILD_SHARED_LIBS=ON -DBUILD_STATIC_LIBS=ON -DBUILD_WITHOUT_LAPACK=no -DNOFORTRAN=0 -DDYNAMIC_ARCH=ON -DCMAKE_BUILD_TYPE=Release"

          cmake .. -G "Ninja" $commonArgs ${{ matrix.target.opts }}

      - name: Build OpenBLAS
        run: |
          cd OpenBLAS
          cd build
          cmake --build . --config Release

      - name: Install OpenBLAS
        run: |
          cd OpenBLAS
          cd build
          cmake --install . --config Release --prefix ../../openblas-windows-latest

      - name: Archive OpenBLAS Build
        uses: actions/upload-artifact@v4
        with:
          name: OpenBLAS-${{ env.OPENBLAS_VERSION }}-MSVC-${{ matrix.target.name }}
          path: openblas-windows-latest
