name: Build OpenBLAS

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  openblas_windows:
    name: Build OpenBLAS on Windows
    runs-on: windows-latest
    env: 
      OPENBLAS_VERSION: 0.3.28

    steps:
      - name: Extract branch name
        shell: bash
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
        id: extract_branch

      - name: Checkout Code
        uses: actions/checkout@v3

      - name: download and unzip OpenBLAS 
        run: |
          curl -LO "https://github.com/OpenMathLib/OpenBLAS/releases/download/v${{ env.OPENBLAS_VERSION }}/OpenBLAS-${{ env.OPENBLAS_VERSION }}.zip"
          7z x "OpenBLAS-${{ env.OPENBLAS_VERSION }}.zip" -oOpenBLAS

      - name: Set Up Miniconda
        uses: conda-incubator/setup-miniconda@v3

      - name: Set Up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.13

      - name: Get Latest CMake and Ninja
        uses: lukka/get-cmake@latest

      - name: Install Conda Packages
        run: |
          conda config --add channels conda-forge --force
          conda config --set auto_update_conda false
          conda install --yes --quiet cmake flang clangdev perl libflang ninja

      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v2

      - name: Configure CMake
        run: |
          #set miniconda library dir
          # set "LIB=%LIB%;%CONDA_PREFIX%\Library\lib"
          conda env
          conda info
          conda list
          dir OpenBLAS
          cd OpenBLAS
          mkdir build
          cd build
          
          $commonArgs = "-DCMAKE_CXX_COMPILER=clang-cl -DCMAKE_C_COMPILER=clang-cl -DCMAKE_Fortran_COMPILER=flang -DCMAKE_MT=mt -DBUILD_SHARED_LIBS=ON -DBUILD_WITHOUT_LAPACK=no -DBINARY=64 -DNOFORTRAN=0 -DDYNAMIC_ARCH=ON -DCMAKE_BUILD_TYPE=Release"

          cmake .. -G "Ninja" $commonArgs

      - name: Build OpenBLAS
        run: |
          cd OpenBLAS
          cd build
          cmake --build . --config Release

      - name: Install OpenBLAS
        run: |
          cd OpenBLAS
          cd build
          cmake --install . --config Release --prefix ../../openblas-windows-latest
      
      - name: Push Changes
        continue-on-error: true
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions@users.noreply.github.com"

          git pull
          git add -A
          git commit -m "Update OpenBLAS on Windows"
          git push origin master

      - name: Archive OpenBLAS Build
        uses: actions/upload-artifact@v4
        with:
          name: OpenBLAS on windows-latest
          path: openblas-windows-latest

